"use client";

import { useEffect, useRef } from "react";
import { SmartSplitResult, Store, StoreId } from "@/lib/types";
import { X, ClipboardCopy, CheckCheck, List } from "lucide-react";
import { useState } from "react";

interface ShoppingListModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: SmartSplitResult;
  stores: Store[];
}

export default function ShoppingListModal({
  isOpen,
  onClose,
  result,
  stores,
}: ShoppingListModalProps) {
  const [copied, setCopied] = useState(false);
  const dialogRef = useRef<HTMLDialogElement>(null);
  const storeMap = new Map(stores.map((s) => [s.id, s]));

  // Sync dialog open/close with DOM
  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (isOpen && !dialog.open) dialog.showModal();
    else if (!isOpen && dialog.open) dialog.close();
  }, [isOpen]);

  // Close on backdrop click
  const handleDialogClick = (e: React.MouseEvent<HTMLDialogElement>) => {
    if (e.target === dialogRef.current) onClose();
  };

  function buildListText(): string {
    const lines: string[] = [
      "🛒 KaiCompare Auckland — Optimised Shopping List",
      "=" .repeat(50),
    ];

    for (const { storeId, storeName, items, storeTotal } of result.splitPlan) {
      const store = storeMap.get(storeId as StoreId);
      lines.push("");
      lines.push(`📍 ${storeName} ${store ? `(${store.branches[0]})` : ""}`);
      lines.push("-".repeat(40));
      for (const item of items) {
        lines.push(`  ☐  ${item.itemName}${item.quantity > 1 ? ` × ${item.quantity}` : ""}  — $${item.lineTotal.toFixed(2)}`);
      }
      lines.push(`  Subtotal: $${storeTotal.toFixed(2)}`);
    }

    lines.push("");
    lines.push("=".repeat(50));
    lines.push(`  SPLIT TOTAL: $${result.splitGrandTotal.toFixed(2)}`);
    if (result.savingsVsSingleCheapest > 0.01) {
      lines.push(`  💰 You save: $${result.savingsVsSingleCheapest.toFixed(2)}`);
    }
    lines.push("=".repeat(50));
    lines.push("Generated by KaiCompare Auckland");
    return lines.join("\n");
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(buildListText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for unsupported contexts
      const ta = document.createElement("textarea");
      ta.value = buildListText();
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  if (!isOpen) return null;

  return (
    <dialog
      ref={dialogRef}
      onClick={handleDialogClick}
      className="w-full max-w-lg rounded-2xl shadow-2xl p-0 border-0 backdrop:bg-black/50 backdrop:backdrop-blur-sm m-auto"
      style={{ maxHeight: "90dvh" }}
    >
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
        <div className="flex items-center gap-2">
          <List className="w-5 h-5 text-amber-500" />
          <h2 className="font-bold text-slate-800 text-lg">Optimised Shopping List</h2>
        </div>
        <button
          onClick={onClose}
          className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-colors"
          aria-label="Close"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      {/* Content */}
      <div className="overflow-y-auto px-5 py-4 space-y-4" style={{ maxHeight: "65dvh" }}>
        {result.splitPlan.length === 0 ? (
          <p className="text-slate-400 text-center py-8">
            Add items to your basket to generate a shopping list.
          </p>
        ) : (
          result.splitPlan.map(({ storeId, storeName, items, storeTotal }) => {
            const store = storeMap.get(storeId as StoreId);
            return (
              <div key={storeId} className="rounded-xl border border-slate-100 overflow-hidden">
                {/* Store header */}
                <div
                  className="flex items-center justify-between px-4 py-2.5"
                  style={{
                    backgroundColor: store?.color ?? "#888",
                    color: store?.textColor ?? "#fff",
                  }}
                >
                  <div className="flex items-center gap-2 font-bold">
                    <span>{store?.logoEmoji}</span>
                    <span>{storeName}</span>
                    {store && (
                      <span className="font-normal opacity-80 text-sm">
                        · {store.branches[0]}
                      </span>
                    )}
                  </div>
                  <span className="font-bold tabular-nums">${storeTotal.toFixed(2)}</span>
                </div>
                {/* Items checklist */}
                <ul className="divide-y divide-slate-50">
                  {items.map((item) => (
                    <li key={item.itemId} className="flex items-center gap-3 px-4 py-2.5">
                      <input
                        type="checkbox"
                        className="w-4 h-4 rounded border-slate-300 accent-emerald-500 cursor-pointer shrink-0"
                        aria-label={`Mark ${item.itemName} as collected`}
                      />
                      <span className="flex-1 text-sm text-slate-700">
                        {item.itemName}
                        {item.quantity > 1 && (
                          <span className="text-slate-400"> × {item.quantity}</span>
                        )}
                      </span>
                      <span className="text-sm font-semibold text-slate-600 tabular-nums">
                        ${item.lineTotal.toFixed(2)}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            );
          })
        )}
      </div>

      {/* Footer */}
      <div className="px-5 py-4 border-t border-slate-100 flex items-center justify-between gap-3">
        <div className="text-sm text-slate-500">
          Split total:{" "}
          <span className="font-bold text-slate-800">${result.splitGrandTotal.toFixed(2)}</span>
          {result.savingsVsSingleCheapest > 0.01 && (
            <span className="ml-2 text-emerald-600 font-semibold">
              (save ${result.savingsVsSingleCheapest.toFixed(2)})
            </span>
          )}
        </div>
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 bg-slate-800 hover:bg-slate-700 text-white text-sm font-semibold px-4 py-2 rounded-xl transition-colors"
        >
          {copied ? (
            <>
              <CheckCheck className="w-4 h-4 text-emerald-400" />
              Copied!
            </>
          ) : (
            <>
              <ClipboardCopy className="w-4 h-4" />
              Copy List
            </>
          )}
        </button>
      </div>
    </dialog>
  );
}
